pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
        // ChaQuopy 的 Gradle 插件
        maven { url 'https://chaquo.com/maven' }
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_PROJECT)
    repositories {
        google()
        mavenCentral()
        maven { url 'https://chaquo.com/maven' }
    }
}
rootProject.name = 'Warehouse'
include ':app'
